/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

/**
 *
 * @author HOANG
 */
public class FrmBaoHanh extends javax.swing.JFrame {

    /**
     * Creates new form FrmBaoHanh
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BaoHanh = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tbpfont2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblbangluuhang = new javax.swing.JTable();
        cbkhongnhanhang = new javax.swing.JCheckBox();
        cbdoimoi = new javax.swing.JCheckBox();
        lbltongcong = new javax.swing.JLabel();
        txttongcong = new javax.swing.JTextField();
        cbbmoney = new javax.swing.JComboBox<String>();
        btnluu = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbltenhang = new javax.swing.JLabel();
        lblsoseri = new javax.swing.JLabel();
        lblmotaloi = new javax.swing.JLabel();
        lblghichu = new javax.swing.JLabel();
        lblnhom = new javax.swing.JLabel();
        lblSL = new javax.swing.JLabel();
        lblgia = new javax.swing.JLabel();
        lblngaymua = new javax.swing.JLabel();
        txttenhang = new javax.swing.JTextField();
        txtsoserri = new javax.swing.JTextField();
        txtmotaloi = new javax.swing.JTextField();
        txtghichu = new javax.swing.JTextField();
        btnghi = new javax.swing.JButton();
        txtsoluong = new javax.swing.JTextField();
        txtgia = new javax.swing.JTextField();
        txtngaymua = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lbltenkhachhang = new javax.swing.JLabel();
        lblmaKH = new javax.swing.JLabel();
        lbldiachi = new javax.swing.JLabel();
        lblghichu1 = new javax.swing.JLabel();
        lbldienthoai = new javax.swing.JLabel();
        txttenhang1 = new javax.swing.JTextField();
        txtsoserri1 = new javax.swing.JTextField();
        txtmotaloi1 = new javax.swing.JTextField();
        txtghichu1 = new javax.swing.JTextField();
        txtsoluong1 = new javax.swing.JTextField();
        cbngayhentra = new javax.swing.JCheckBox();
        spndate = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        lblngay = new javax.swing.JLabel();
        spnngay = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spnngay2 = new javax.swing.JSpinner();
        cbbBCnhanbaohanh = new javax.swing.JComboBox<String>();
        btntim = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbbbaocaonhanbaohanh = new javax.swing.JTable();
        btnxoa = new javax.swing.JButton();
        llbltongcong = new javax.swing.JLabel();
        txttongcong2 = new javax.swing.JTextField();
        cbmanhanvien = new javax.swing.JCheckBox();
        cbsoct = new javax.swing.JCheckBox();
        cbbsoseri = new javax.swing.JCheckBox();
        cbbmotaloi = new javax.swing.JCheckBox();
        cbbgiasuachua = new javax.swing.JCheckBox();
        cbghichu = new javax.swing.JCheckBox();
        cbngaymua = new javax.swing.JCheckBox();
        cbNgayhentra = new javax.swing.JCheckBox();
        cbNgaytra = new javax.swing.JCheckBox();
        cbtrahang = new javax.swing.JCheckBox();
        cbghichudonhang = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        lbltenhang8 = new javax.swing.JLabel();
        lblsoseri8 = new javax.swing.JLabel();
        lblmotaloi8 = new javax.swing.JLabel();
        lblghichu9 = new javax.swing.JLabel();
        lblnhom8 = new javax.swing.JLabel();
        lblSL8 = new javax.swing.JLabel();
        txttenhang9 = new javax.swing.JTextField();
        txtsoserri9 = new javax.swing.JTextField();
        txtmotaloi9 = new javax.swing.JTextField();
        txtghichu9 = new javax.swing.JTextField();
        btnghi8 = new javax.swing.JButton();
        txtsoluong9 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<String>();
        jPanel29 = new javax.swing.JPanel();
        lbltenkhachhang1 = new javax.swing.JLabel();
        lblmaKH1 = new javax.swing.JLabel();
        lbldiachi1 = new javax.swing.JLabel();
        lblghichu10 = new javax.swing.JLabel();
        lbldienthoai1 = new javax.swing.JLabel();
        txttenhang10 = new javax.swing.JTextField();
        txtsoserri10 = new javax.swing.JTextField();
        txtmotaloi10 = new javax.swing.JTextField();
        txtghichu10 = new javax.swing.JTextField();
        txtsoluong10 = new javax.swing.JTextField();
        cbngayhentra1 = new javax.swing.JCheckBox();
        spndate1 = new javax.swing.JSpinner();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblbangluuhang6 = new javax.swing.JTable();
        btnhuy2 = new javax.swing.JButton();
        btnluu2 = new javax.swing.JButton();
        btnxoaaa = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lblngay2 = new javax.swing.JLabel();
        spngay = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spngay2 = new javax.swing.JSpinner();
        cbbbaocaoguibaohanh = new javax.swing.JComboBox<String>();
        bttntim2 = new javax.swing.JButton();
        btnxuat2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbbguibaocaobaohanh = new javax.swing.JTable();
        cbmanhanvien2 = new javax.swing.JCheckBox();
        cbsocongtac = new javax.swing.JCheckBox();
        cbbsoserii = new javax.swing.JCheckBox();
        cbmotaloi2 = new javax.swing.JCheckBox();
        cbghichu2 = new javax.swing.JCheckBox();
        cbngaytra2 = new javax.swing.JCheckBox();
        cbghichudonhang2 = new javax.swing.JCheckBox();
        cbtrahang2 = new javax.swing.JCheckBox();
        btxoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tbntonkho = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnintonkho = new javax.swing.JButton();
        btnnhapp = new javax.swing.JButton();
        btnxuatt = new javax.swing.JButton();
        lblsoluongg = new javax.swing.JLabel();
        txtsoluongg = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbbbaocaotonkho = new javax.swing.JTable();
        lblngaykho = new javax.swing.JLabel();
        spnngaykho = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spnngaykho2 = new javax.swing.JSpinner();
        cbbtonkho = new javax.swing.JComboBox<String>();
        btntimm = new javax.swing.JButton();
        btnxuattt = new javax.swing.JButton();
        btnxoaa = new javax.swing.JButton();
        cbmaNV = new javax.swing.JCheckBox();
        cbsochungtu = new javax.swing.JCheckBox();
        cbghichuu = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BaoHanh.setBackground(new java.awt.Color(102, 102, 255));
        BaoHanh.setForeground(new java.awt.Color(51, 0, 51));
        BaoHanh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        tbpfont2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tblbangluuhang.setBackground(new java.awt.Color(240, 240, 240));
        tblbangluuhang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblbangluuhang.setForeground(new java.awt.Color(51, 0, 51));
        tblbangluuhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Hàng", "Số seri", "Mô tả lỗi", "Số lượng", "Giá sửa chửa", "Ngày mua", "Ghi chú"
            }
        ));
        tblbangluuhang.setGridColor(new java.awt.Color(0, 0, 0));
        tblbangluuhang.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane3.setViewportView(tblbangluuhang);

        buttonGroup1.add(cbkhongnhanhang);
        cbkhongnhanhang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbkhongnhanhang.setText("Không nhận hàng");

        buttonGroup1.add(cbdoimoi);
        cbdoimoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbdoimoi.setText("Đổi mới");

        lbltongcong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbltongcong.setForeground(new java.awt.Color(0, 51, 153));
        lbltongcong.setText("Tổng cộng:");

        cbbmoney.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbbmoney.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tiền", "Tièn" }));

        btnluu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/45.png"))); // NOI18N
        btnluu.setText("Lưu");

        btnhuy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnhuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Remove.png"))); // NOI18N
        btnhuy.setText("Hủy");

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jPanel6.setForeground(new java.awt.Color(240, 240, 240));
        jPanel6.setAutoscrolls(true);

        lbltenhang.setText("Tên Hàng:");

        lblsoseri.setText("Số seri:");

        lblmotaloi.setText("Mô tả lỗi:");

        lblghichu.setText("Ghi chú:");

        lblnhom.setText("Nhóm:");

        lblSL.setText("Số lượng:");

        lblgia.setText("Giá:");

        lblngaymua.setText("Ngày mua:");

        btnghi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnghi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnghi.setText("Ghi");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblmotaloi)
                                .addGap(213, 213, 213))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblghichu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblngaymua)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblgia)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(lblsoseri)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtmotaloi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtsoserri, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtngaymua, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                            .addComponent(txtgia)
                                            .addComponent(txtsoluong)))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(lbltenhang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txttenhang, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(lblnhom)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(btnghi)
                                        .addGap(18, 18, 18)))))
                        .addGap(2, 2, 2))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltenhang)
                    .addComponent(lblnhom)
                    .addComponent(txttenhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsoseri)
                    .addComponent(lblSL)
                    .addComponent(txtsoserri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmotaloi)
                    .addComponent(lblgia)
                    .addComponent(txtmotaloi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblghichu)
                    .addComponent(lblngaymua)
                    .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaymua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnghi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jPanel8.setForeground(new java.awt.Color(240, 240, 240));
        jPanel8.setAutoscrolls(true);

        lbltenkhachhang.setText("Tên Khách Hàng:");

        lblmaKH.setText("Mã KH:");

        lbldiachi.setText("Địa chỉ:");

        lblghichu1.setText("Ghi chú:");

        lbldienthoai.setText("ĐT:");

        txtsoluong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluong1ActionPerformed(evt);
            }
        });

        cbngayhentra.setText("Ngày hẹn trả");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblmaKH)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lbltenkhachhang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtsoserri1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbldienthoai)
                                        .addGap(1, 1, 1)
                                        .addComponent(txtsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txttenhang1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                    .addComponent(txtmotaloi1)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldiachi)
                                    .addComponent(lblghichu1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(cbngayhentra)
                                        .addGap(18, 18, 18)
                                        .addComponent(spndate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtghichu1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltenkhachhang)
                    .addComponent(txttenhang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmaKH)
                    .addComponent(lbldienthoai)
                    .addComponent(txtsoserri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiachi)
                    .addComponent(txtmotaloi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblghichu1)
                    .addComponent(txtghichu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbngayhentra)
                    .addComponent(spndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cbkhongnhanhang)
                        .addGap(18, 18, 18)
                        .addComponent(cbdoimoi)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbltongcong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbbmoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnluu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhuy)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbkhongnhanhang)
                            .addComponent(cbdoimoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltongcong)
                            .addComponent(txttongcong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnluu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbmoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnhuy)))))
                .addContainerGap())
        );

        tbpfont2.addTab("NHẬN BẢO HÀNH", jPanel4);

        lblngay.setText("Ngày:");

        jLabel1.setText("-");

        cbbBCnhanbaohanh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chưa thanh toán", "Item 2", "Item 3", "Item 4" }));

        btntim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search-icon.png"))); // NOI18N
        btntim.setText("Tìm");

        btnxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Update.png"))); // NOI18N
        btnxuat.setText("Xuất");

        tbbbaocaonhanbaohanh.setBackground(new java.awt.Color(240, 240, 240));
        tbbbaocaonhanbaohanh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbbbaocaonhanbaohanh.setForeground(new java.awt.Color(51, 0, 51));
        tbbbaocaonhanbaohanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày", "Khách hàng", "Tên hàng", "Số seri", "Mô tả lỗi", "Số lượng", "Giá sửa chữa"
            }
        ));
        tbbbaocaonhanbaohanh.setGridColor(new java.awt.Color(0, 0, 0));
        tbbbaocaonhanbaohanh.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane4.setViewportView(tbbbaocaonhanbaohanh);
        if (tbbbaocaonhanbaohanh.getColumnModel().getColumnCount() > 0) {
            tbbbaocaonhanbaohanh.getColumnModel().getColumn(7).setHeaderValue("Giá sửa chữa");
        }

        btnxoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnxoa.setText("Xóa");

        llbltongcong.setText("Tổng cộng:");

        cbmanhanvien.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbmanhanvien.setText("Mã nhân viên");
        cbmanhanvien.setToolTipText("");

        cbsoct.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbsoct.setText("Số CT");
        cbsoct.setToolTipText("");

        cbbsoseri.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbbsoseri.setText("Số Seri");
        cbbsoseri.setToolTipText("");

        cbbmotaloi.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbbmotaloi.setText("Mô tả lỗi");
        cbbmotaloi.setToolTipText("");

        cbbgiasuachua.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbbgiasuachua.setText("Giá sửa chữa");
        cbbgiasuachua.setToolTipText("");

        cbghichu.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbghichu.setText("Ghi chú");
        cbghichu.setToolTipText("");

        cbngaymua.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbngaymua.setText("Ngày mua");
        cbngaymua.setToolTipText("");
        cbngaymua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbngaymuaActionPerformed(evt);
            }
        });

        cbNgayhentra.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbNgayhentra.setText("Ngày hẹn trả");
        cbNgayhentra.setToolTipText("");

        cbNgaytra.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbNgaytra.setText("Ngày  trả");
        cbNgaytra.setToolTipText("");

        cbtrahang.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbtrahang.setText("Trả hàng");
        cbtrahang.setToolTipText("");

        cbghichudonhang.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbghichudonhang.setText("Ghi chú đơn hàng");
        cbghichudonhang.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblngay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnngay, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnngay2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbbBCnhanbaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btntim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxuat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(cbmanhanvien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbsoct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbsoseri)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbmotaloi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbgiasuachua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbghichu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbngaymua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbNgayhentra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbNgaytra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbghichudonhang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbtrahang))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnxoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(llbltongcong)
                                .addGap(18, 18, 18)
                                .addComponent(txttongcong2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
            .addComponent(jScrollPane4)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblngay)
                    .addComponent(spnngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(spnngay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbBCnhanbaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntim)
                    .addComponent(btnxuat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoa)
                    .addComponent(llbltongcong)
                    .addComponent(txttongcong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmanhanvien)
                    .addComponent(cbsoct)
                    .addComponent(cbbsoseri)
                    .addComponent(cbbmotaloi)
                    .addComponent(cbbgiasuachua)
                    .addComponent(cbghichu)
                    .addComponent(cbngaymua)
                    .addComponent(cbNgayhentra)
                    .addComponent(cbNgaytra)
                    .addComponent(cbtrahang)
                    .addComponent(cbghichudonhang)))
        );

        tbpfont2.addTab("BÁO CÁO", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpfont2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpfont2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        BaoHanh.addTab("NHẬN BẢO HÀNH", jPanel2);

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jPanel28.setForeground(new java.awt.Color(240, 240, 240));
        jPanel28.setAutoscrolls(true);

        lbltenhang8.setText("Tên Hàng:");

        lblsoseri8.setText("Số seri:");

        lblmotaloi8.setText("Mô tả lỗi:");

        lblghichu9.setText("Ghi chú:");

        lblnhom8.setText("Nhóm:");

        lblSL8.setText("Số lượng:");

        btnghi8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnghi8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnghi8.setText("Ghi");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblmotaloi8)
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(lblghichu9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(txtghichu9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(lbltenhang8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttenhang9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblnhom8)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel28Layout.createSequentialGroup()
                                .addComponent(lblsoseri8)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel28Layout.createSequentialGroup()
                                        .addComponent(txtmotaloi9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnghi8))
                                    .addGroup(jPanel28Layout.createSequentialGroup()
                                        .addComponent(txtsoserri9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSL8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                        .addComponent(txtsoluong9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(2, 2, 2))))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltenhang8)
                    .addComponent(lblnhom8)
                    .addComponent(txttenhang9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsoseri8)
                    .addComponent(lblSL8)
                    .addComponent(txtsoserri9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluong9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmotaloi8)
                            .addComponent(txtmotaloi9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblghichu9)
                            .addComponent(txtghichu9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnghi8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        jPanel29.setForeground(new java.awt.Color(240, 240, 240));
        jPanel29.setAutoscrolls(true);

        lbltenkhachhang1.setText("Tên Khách Hàng:");

        lblmaKH1.setText("Mã KH:");

        lbldiachi1.setText("Địa chỉ:");

        lblghichu10.setText("Ghi chú:");

        lbldienthoai1.setText("ĐT:");

        txtsoluong10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluong10ActionPerformed(evt);
            }
        });

        cbngayhentra1.setText("Ngày hẹn trả");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addComponent(lblmaKH1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel29Layout.createSequentialGroup()
                                .addComponent(lbltenkhachhang1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel29Layout.createSequentialGroup()
                                        .addComponent(txtsoserri10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbldienthoai1)
                                        .addGap(1, 1, 1)
                                        .addComponent(txtsoluong10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txttenhang10, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                    .addComponent(txtmotaloi10)))
                            .addGroup(jPanel29Layout.createSequentialGroup()
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldiachi1)
                                    .addComponent(lblghichu10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel29Layout.createSequentialGroup()
                                        .addComponent(cbngayhentra1)
                                        .addGap(18, 18, 18)
                                        .addComponent(spndate1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtghichu10, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltenkhachhang1)
                    .addComponent(txttenhang10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmaKH1)
                    .addComponent(lbldienthoai1)
                    .addComponent(txtsoserri10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluong10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiachi1)
                    .addComponent(txtmotaloi10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblghichu10)
                    .addComponent(txtghichu10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbngayhentra1)
                    .addComponent(spndate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tblbangluuhang6.setBackground(new java.awt.Color(240, 240, 240));
        tblbangluuhang6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblbangluuhang6.setForeground(new java.awt.Color(51, 0, 51));
        tblbangluuhang6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Hàng", "Số seri", "Mô tả lỗi", "Số lượng", "Giá sửa chửa", "Ngày mua", "Ghi chú"
            }
        ));
        tblbangluuhang6.setGridColor(new java.awt.Color(0, 0, 0));
        tblbangluuhang6.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane9.setViewportView(tblbangluuhang6);

        btnhuy2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnhuy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Remove.png"))); // NOI18N
        btnhuy2.setText("Hủy");

        btnluu2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnluu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        btnluu2.setText("Lưu");

        btnxoaaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnxoaaa.setText("Xóa");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnxoaaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnluu2)
                .addGap(18, 18, 18)
                .addComponent(btnhuy2)
                .addGap(43, 43, 43))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnluu2)
                    .addComponent(btnhuy2)
                    .addComponent(btnxoaaa))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GỬI BẢO HÀNH", jPanel9);

        lblngay2.setText("Ngày:");

        jLabel2.setText("-");

        cbbbaocaoguibaohanh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chưa trả hàng", "Item 2", "Item 3", "Item 4" }));

        bttntim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search-icon.png"))); // NOI18N
        bttntim2.setText("Tìm");

        btnxuat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Update.png"))); // NOI18N
        btnxuat2.setText("Xuất");

        tbbguibaocaobaohanh.setBackground(new java.awt.Color(240, 240, 240));
        tbbguibaocaobaohanh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbbguibaocaobaohanh.setForeground(new java.awt.Color(51, 0, 51));
        tbbguibaocaobaohanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày", "Khách hàng", "Tên hàng", "Số seri", "Mô tả lỗi", "Số lượng"
            }
        ));
        tbbguibaocaobaohanh.setGridColor(new java.awt.Color(0, 0, 0));
        tbbguibaocaobaohanh.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane5.setViewportView(tbbguibaocaobaohanh);

        cbmanhanvien2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbmanhanvien2.setText("Mã nhân viên");

        cbsocongtac.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbsocongtac.setText("Số CT");

        cbbsoserii.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbbsoserii.setText("Số seri");

        cbmotaloi2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbmotaloi2.setText("Mô tả lỗi");
        cbmotaloi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmotaloi2ActionPerformed(evt);
            }
        });

        cbghichu2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbghichu2.setText("Ghi chú");

        cbngaytra2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbngaytra2.setText("Ngày trả");

        cbghichudonhang2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbghichudonhang2.setText("Ghi chú đơn hàng");

        cbtrahang2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cbtrahang2.setText("Trả hàng");

        btxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btxoa.setText("Xóa");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lblngay2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spngay, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(spngay2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbbaocaoguibaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttntim2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnxuat2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                        .addComponent(cbmanhanvien2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbsocongtac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbsoserii)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbmotaloi2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbghichu2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbngaytra2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbghichudonhang2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbtrahang2)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblngay2)
                    .addComponent(spngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spngay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbbaocaoguibaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttntim2)
                    .addComponent(btnxuat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbmanhanvien2)
                            .addComponent(cbsocongtac)
                            .addComponent(cbbsoserii)
                            .addComponent(cbmotaloi2)
                            .addComponent(cbghichu2)
                            .addComponent(cbngaytra2)
                            .addComponent(cbghichudonhang2)
                            .addComponent(cbtrahang2)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btxoa)
                        .addGap(0, 21, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("BÁO CÁO", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        BaoHanh.addTab("GỬI BẢO HÀNH", jPanel3);

        tbntonkho.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tbntonkho.setForeground(new java.awt.Color(0, 0, 255));
        tbntonkho.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, 0, 256, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(570, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Hàng", "Đơn vị", "Số lượng", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnintonkho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign-up-icon (1).png"))); // NOI18N
        btnintonkho.setText("In tồn kho");

        btnnhapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Fast-backward-icon.png"))); // NOI18N
        btnnhapp.setText("Nhập");
        btnnhapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnhappMouseClicked(evt);
            }
        });

        btnxuatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Fast-forward-icon.png"))); // NOI18N
        btnxuatt.setText("Xuất");

        lblsoluongg.setText("Số lượng:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnintonkho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnhapp)
                        .addGap(18, 18, 18)
                        .addComponent(btnxuatt)
                        .addGap(183, 183, 183)
                        .addComponent(lblsoluongg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsoluongg, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnintonkho)
                        .addComponent(btnnhapp)
                        .addComponent(btnxuatt))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblsoluongg)
                        .addComponent(txtsoluongg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbntonkho.addTab("TỒN KHO", jPanel11);

        tbbbaocaotonkho.setBackground(new java.awt.Color(240, 240, 240));
        tbbbaocaotonkho.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbbbaocaotonkho.setForeground(new java.awt.Color(51, 0, 51));
        tbbbaocaotonkho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày", "Khách hàng", "Tên hàng", "Số seri", "Mô tả lỗi", "Số lượng"
            }
        ));
        tbbbaocaotonkho.setGridColor(new java.awt.Color(0, 0, 0));
        tbbbaocaotonkho.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jScrollPane6.setViewportView(tbbbaocaotonkho);

        lblngaykho.setText("Ngày:");

        jLabel3.setText("-");

        cbbtonkho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Item 2", "Item 3", "Item 4" }));

        btntimm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search-icon.png"))); // NOI18N
        btntimm.setText("Tìm");

        btnxuattt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Update.png"))); // NOI18N
        btnxuattt.setText("Xuất");

        btnxoaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnxoaa.setText("Xóa");

        cbmaNV.setText("Mã nhân viên");

        cbsochungtu.setText("Số chứng từ");

        cbghichuu.setText("Ghi chú");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(lblngaykho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnngaykho, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnngaykho2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbbtonkho, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntimm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnxuattt)
                        .addContainerGap(394, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnxoaa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbmaNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbsochungtu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbghichuu)
                        .addGap(20, 20, 20))))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblngaykho)
                    .addComponent(spnngaykho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spnngaykho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbtonkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimm)
                    .addComponent(btnxuattt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 515, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoaa)
                    .addComponent(cbmaNV)
                    .addComponent(cbsochungtu)
                    .addComponent(cbghichuu))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        tbntonkho.addTab("BÁO CÁO", jPanel12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbntonkho)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbntonkho)
        );

        BaoHanh.addTab("TỒN KHO", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BaoHanh)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsoluong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluong1ActionPerformed

    private void txtsoluong10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluong10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluong10ActionPerformed

    private void cbngaymuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbngaymuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbngaymuaActionPerformed

    private void cbmotaloi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmotaloi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmotaloi2ActionPerformed

    private void btnnhappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnhappMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnhappMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBaoHanh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BaoHanh;
    private javax.swing.JButton btnghi;
    private javax.swing.JButton btnghi8;
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnhuy2;
    private javax.swing.JButton btnintonkho;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnluu2;
    private javax.swing.JButton btnnhapp;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btntimm;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxoaa;
    private javax.swing.JButton btnxoaaa;
    private javax.swing.JButton btnxuat;
    private javax.swing.JButton btnxuat2;
    private javax.swing.JButton btnxuatt;
    private javax.swing.JButton btnxuattt;
    private javax.swing.JButton bttntim2;
    private javax.swing.JButton btxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbNgayhentra;
    private javax.swing.JCheckBox cbNgaytra;
    private javax.swing.JComboBox<String> cbbBCnhanbaohanh;
    private javax.swing.JComboBox<String> cbbbaocaoguibaohanh;
    private javax.swing.JCheckBox cbbgiasuachua;
    private javax.swing.JComboBox<String> cbbmoney;
    private javax.swing.JCheckBox cbbmotaloi;
    private javax.swing.JCheckBox cbbsoseri;
    private javax.swing.JCheckBox cbbsoserii;
    private javax.swing.JComboBox<String> cbbtonkho;
    private javax.swing.JCheckBox cbdoimoi;
    private javax.swing.JCheckBox cbghichu;
    private javax.swing.JCheckBox cbghichu2;
    private javax.swing.JCheckBox cbghichudonhang;
    private javax.swing.JCheckBox cbghichudonhang2;
    private javax.swing.JCheckBox cbghichuu;
    private javax.swing.JCheckBox cbkhongnhanhang;
    private javax.swing.JCheckBox cbmaNV;
    private javax.swing.JCheckBox cbmanhanvien;
    private javax.swing.JCheckBox cbmanhanvien2;
    private javax.swing.JCheckBox cbmotaloi2;
    private javax.swing.JCheckBox cbngayhentra;
    private javax.swing.JCheckBox cbngayhentra1;
    private javax.swing.JCheckBox cbngaymua;
    private javax.swing.JCheckBox cbngaytra2;
    private javax.swing.JCheckBox cbsochungtu;
    private javax.swing.JCheckBox cbsocongtac;
    private javax.swing.JCheckBox cbsoct;
    private javax.swing.JCheckBox cbtrahang;
    private javax.swing.JCheckBox cbtrahang2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSL;
    private javax.swing.JLabel lblSL8;
    private javax.swing.JLabel lbldiachi;
    private javax.swing.JLabel lbldiachi1;
    private javax.swing.JLabel lbldienthoai;
    private javax.swing.JLabel lbldienthoai1;
    private javax.swing.JLabel lblghichu;
    private javax.swing.JLabel lblghichu1;
    private javax.swing.JLabel lblghichu10;
    private javax.swing.JLabel lblghichu9;
    private javax.swing.JLabel lblgia;
    private javax.swing.JLabel lblmaKH;
    private javax.swing.JLabel lblmaKH1;
    private javax.swing.JLabel lblmotaloi;
    private javax.swing.JLabel lblmotaloi8;
    private javax.swing.JLabel lblngay;
    private javax.swing.JLabel lblngay2;
    private javax.swing.JLabel lblngaykho;
    private javax.swing.JLabel lblngaymua;
    private javax.swing.JLabel lblnhom;
    private javax.swing.JLabel lblnhom8;
    private javax.swing.JLabel lblsoluongg;
    private javax.swing.JLabel lblsoseri;
    private javax.swing.JLabel lblsoseri8;
    private javax.swing.JLabel lbltenhang;
    private javax.swing.JLabel lbltenhang8;
    private javax.swing.JLabel lbltenkhachhang;
    private javax.swing.JLabel lbltenkhachhang1;
    private javax.swing.JLabel lbltongcong;
    private javax.swing.JLabel llbltongcong;
    private javax.swing.JSpinner spndate;
    private javax.swing.JSpinner spndate1;
    private javax.swing.JSpinner spngay;
    private javax.swing.JSpinner spngay2;
    private javax.swing.JSpinner spnngay;
    private javax.swing.JSpinner spnngay2;
    private javax.swing.JSpinner spnngaykho;
    private javax.swing.JSpinner spnngaykho2;
    private javax.swing.JTable tbbbaocaonhanbaohanh;
    private javax.swing.JTable tbbbaocaotonkho;
    private javax.swing.JTable tbbguibaocaobaohanh;
    private javax.swing.JTable tblbangluuhang;
    private javax.swing.JTable tblbangluuhang6;
    private javax.swing.JTabbedPane tbntonkho;
    private javax.swing.JTabbedPane tbpfont2;
    private javax.swing.JTextField txtghichu;
    private javax.swing.JTextField txtghichu1;
    private javax.swing.JTextField txtghichu10;
    private javax.swing.JTextField txtghichu9;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtmotaloi;
    private javax.swing.JTextField txtmotaloi1;
    private javax.swing.JTextField txtmotaloi10;
    private javax.swing.JTextField txtmotaloi9;
    private javax.swing.JTextField txtngaymua;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtsoluong1;
    private javax.swing.JTextField txtsoluong10;
    private javax.swing.JTextField txtsoluong9;
    private javax.swing.JTextField txtsoluongg;
    private javax.swing.JTextField txtsoserri;
    private javax.swing.JTextField txtsoserri1;
    private javax.swing.JTextField txtsoserri10;
    private javax.swing.JTextField txtsoserri9;
    private javax.swing.JTextField txttenhang;
    private javax.swing.JTextField txttenhang1;
    private javax.swing.JTextField txttenhang10;
    private javax.swing.JTextField txttenhang9;
    private javax.swing.JTextField txttongcong;
    private javax.swing.JTextField txttongcong2;
    // End of variables declaration//GEN-END:variables
}
